### ISSUE TITLE
Glusterfs - 6.0.0 Dockerfile and Image

### ISSUE THREAD

**Issue by aakarshit-batchu** [gluster/gluster-containers#140]
Hi Team,

We are actually facing this issue - https://bugzilla.redhat.com/show_bug.cgi?id=1596787 with the glusterfs - 4.* and the latest glusterfs images that are available are 4.* images only. And we have come across the release notes of glusterfs - 6.0.0 where they have addressed that they resolved that bug - https://docs.gluster.org/en/latest/release-notes/6.0/ . So kindly release the glusterfs - 6.0.0 images at the earliest, so that we can start using that image.

Thanks in Advance!

**Comment by kannanvj** [comment]
Hi All,
   I am also facing the similar issue .... When we rebooted the node one by one, glusterfs and heketi comes back normally. But when we try to create the PVC, it is in pending state. Existing PVC is working fine... But We could not create the new PVC... When we understand the issue, we observe that Volume create request is received by Heketi. But Heketi is not responding back anything. Aslo,We observed that Heketi health check was completely stopped with glusterfs.
Glusterfs, we have observed so many error log... ALl the error log is similar to the Bug mentioned by @aakarshit-batchu ....
Kindly provide the fix for this issue... It seems it is fixed in the 6.0 version. But it is not available

**Comment by jomeier** [comment]
Hi,

another critical bug seems to be fixed with glusterfs 6.0 :

https://github.com/gluster/glusterfs/issues/625

With our script you can get gluster prior v5 to run amok. 

Update the image to version 6 if it's possible, please.

Thank you and best regards,

Josef

**Comment by kannanvr** [comment]
@jomeier , Thanks for your reply...
We would like to upgrade the image version 6 for glusterfs. 
Currently we are using the Glusterfs conainer image "gluster/gluster-centos:gluster4u0_centos7" along with heketi-7
How to get the image for glusterfs version 6.0... 
Kindly help us which script we need to run to build the glusterfs version 6.0.

Thanks,
Kannan V

**Comment by jomeier** [comment]
@kannanvr:
I'm not one of the maintainers of this project.

But... 

```
cd CentOS
docker build -t gluster-centos .
```

will build the image.

We had a problem that the listen-port parameter for glusterd was not set to port 24007 in the file

/etc/glusterfs/glusterd.vol

The file should look similar to this:

```
volume management
    type mgmt/glusterd
    option working-directory /var/lib/glusterd
    option transport-type socket,rdma
    option transport.socket.keepalive-time 10
    option transport.socket.keepalive-interval 2
    option transport.socket.read-fail-log off
    option transport.socket.listen-port 24007
    option transport.rdma.listen-port 24008
    option ping-timeout 0
    option event-threads 1
#   option lock-timer 180
#   option transport.address-family inet6
#   option base-port 49152
#   option max-port  65535
```

Don't know why this parameters are missing in the image for gluster v6.

**Comment by jomeier** [comment]
Ignore my comment about missing entries in the glusterd.vol file. 

I rebuilt the docker image for gluster 6 and now everything seems to work out of the box on the first sight with the commands in the first half of my post.

**Comment by kannanvj** [comment]
@jomeier Thanks Jomeier. We will also build the image and test it... Once again thanks a lot for your help

**Comment by kannanvr** [comment]
I am able to create the glusterfs image of version 6.0 ...
I have also observed that 24007 port is exposed and glusterd is listening on this port number
But When i am running with Heketi, it could not mount the volume of heketidbstorage within heketi pod. Also, I have tried  mounting  the volume manually.. glusterfs  is throwing the below error

```
  Warning  FailedMount  7m22s  kubelet, uklab16  MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/a1aa12b4-5d07-11e9-8909-14feb501f21c/volumes/kubernetes.io~glusterfs/heketi-storage --scope -- mount -t glusterfs -o auto_unmount,backup-volfile-servers=10.71.3.10:10.71.3.14:10.71.3.16,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/heketi-storage/heketi-storage-copy-job-tdp4r-glusterfs.log,log-level=ERROR 10.71.3.10:heketidbstorage /var/lib/kubelet/pods/a1aa12b4-5d07-11e9-8909-14feb501f21c/volumes/kubernetes.io~glusterfs/heketi-storage
Output: Running scope as unit run-16095.scope.
Mount failed. Please check the log file for more details.

 the following error information was pulled from the glusterfs log to help diagnose this issue:
[2019-04-12 09:46:02.658890] E [MSGID: 100026] [glusterfsd.c:2351:glusterfs_process_volfp] 0-: failed to construct the graph
[2019-04-12 09:46:02.659206] E [graph.c:1142:glusterfs_graph_destroy] (-->/usr/sbin/glusterfs(mgmt_getspec_cbk+0x532) [0x5616ba45d332] -->/usr/sbin/glusterfs(glusterfs_process_volfp+0x150) [0x5616ba456e60] -->/lib64/libglusterfs.so.0(glusterfs_graph_destroy+0x84) [0x7ff2df2901e4] ) 0-graph: invalid argument: graph [Invalid argument]
  Warning  FailedMount  110s (x3 over 6m24s)  kubelet, uklab16  Unable to mount volumes for pod "heketi-storage-copy-job-tdp4r_default(a1aa12b4-5d07-11e9-8909-14feb501f21c)": timeout expired waiting for volumes to attach or mount for pod "default"/"heketi-storage-copy-job-tdp4r". list of unmounted volumes=[heketi-storage]. list of unattached volumes=[heketi-storage heketi-storage-secret default-token-56fwc]
  Warning  FailedMount  11s (x4 over 6m18s)   kubelet, uklab16  (combined from similar events): MountVolume.SetUp failed for volume "heketi-storage" : mount failed: mount failed: exit status 1
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/a1aa12b4-5d07-11e9-8909-14feb501f21c/volumes/kubernetes.io~glusterfs/heketi-storage --scope -- mount -t glusterfs -o auto_unmount,backup-volfile-servers=10.71.3.10:10.71.3.14:10.71.3.16,log-file=/var/lib/kubelet/plugins/kubernetes.io/glusterfs/heketi-storage/heketi-storage-copy-job-tdp4r-glusterfs.log,log-level=ERROR 10.71.3.10:heketidbstorage /var/lib/kubelet/pods/a1aa12b4-5d07-11e9-8909-14feb501f21c/volumes/kubernetes.io~glusterfs/heketi-storage
Output: Running scope as unit run-22254.scope.
Mount failed. Please check the log file for more details.

 the following error information was pulled from the glusterfs log to help diagnose this issue:
[2019-04-12 09:53:13.625586] E [MSGID: 100026] [glusterfsd.c:2351:glusterfs_process_volfp] 0-: failed to construct the graph
[2019-04-12 09:53:13.625895] E [graph.c:1142:glusterfs_graph_destroy] (-->/usr/sbin/glusterfs(mgmt_getspec_cbk+0x532) [0x55be32768332] -->/usr/sbin/glusterfs(glusterfs_process_volfp+0x150) [0x55be32761e60] -->/lib64/libglusterfs.so.0(glusterfs_graph_destroy+0x84) [0x7f7358be71e4] ) 0-graph: invalid argument: graph [Invalid argument]
```
How to resolve this mount issue on glusterfs 6.0 version.
Due to this issue , Heketi pod could not come up as a Running state. I have keep observed the above error.

Request you to help us to solve this issue... We wanted to run Heketi with Glusterfs version 6 on our cluster

Thanks,
Kannan V

**Comment by kannanvr** [comment]
@jomeier , Kindly provide your suggestion to resolve this issue...

**Comment by jomeier** [comment]
gluster-fuse on the host must have the same version as the gluster image.

Maybe thats the problem?

**Comment by kannanvr** [comment]
@jomeier Thanks for your suggestion. It works ... After upgrading the gluster-fuse, it works fine

**Comment by howels** [comment]
Is there a plan to add 5.x and 6.x images to Dockerhub?  The :latest tag retrieves a 4.x image at present.

**Comment by kannanvr** [comment]
@jomeier We have upgraded the glusterfs due to the issue observed after the node reboot. We could not recover the bricks after the node reboot.It is always showing "Transport endpoint not connected" Still In release 6 also, I am observing the same after rebooting the node 2 or 3 times. Do you have any suggestions or recommendations to recover the brick during this situations?

I have raised the issue on glusterfs project. but No reply yet. Just with the curiosity, I am asking this question on gluster-container project...

Kindly provide your valuable suggestion to resolve these issues...

**Comment by aakarshit-batchu** [comment]
Thanks for the help @jomeier 
Closing the issue.
